name: Publish to NPM and GitHub Package Registry

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Publish to GitHub Package Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${GH_TOKEN}" > .npmrc
          npm publish --registry=https://npm.pkg.github.com
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
